version: "3.8"

services:

  golang:
    build:
      context: .
      args:
        - arch=
        - version=1.13.14
        - build=dev
    image: leadstec.tencentcloudcr.com/leadstec/golang:1.13.14
    ports:
      - "50701:5000"
    volumes:
      - ~/volumes/golang.local/log:/data/log
      - ~/volumes/golang.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - EMAIL=
    hostname: golang.local
    container_name: golang.local
