version: "3.8"

services:

  golang:
    build:
      context: .
    image: leadstec/golang:1.13
    ports:
      - "50701:5000"
    volumes:
      - ~/volumes/golang.local/log:/data/log
      - ~/volumes/golang.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - EMAIL=
    hostname: golang.local
    container_name: golang.local
