#!/bin/bash

set -e

clog -t "golang: Build process start ..."

# add image schema
lcs-cli schema add --section golang

# Create the golang user and group
adduser -h /home/go -s /bin/bash -D go
passwd -d go
# Add go to wheel
addgroup go wheel
clog -i "golang: go user and group created."

# change go to ownership of ${APP_DIR}
chown -R go:lcs ${APP_DIR}
clog -i "golang: Fixed ownership of ${APP_DIR}"

# complete
clog -t "golang: Build process completed."
